spring.application.name=novawallet-api
server.port=8080

# H2 in-memory database for development (replaced by PostgreSQL later)
spring.datasource.url=jdbc:h2:mem:novawallet
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Disable Flyway until Day 21
spring.flyway.enabled=false
