spring:
  application:
    name: novawallet-api

  profiles:
    active: dev

  jpa:
    open-in-view: false

  jackson:
    serialization:
      write-dates-as-timestamps: false


server:
  servlet:
    context-path: /api


management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

  info:
    env:
      enabled: true


info:
  app:
    name: NovaWallet API
    description: Digital wallet backend system
    version: 0.0.1


logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{requestId}] %-5level %logger{36} - %msg%n"


springdoc:
  swagger-ui:
    path: /swagger-ui.html

  api-docs:
    path: /api-docs